// videos.ts

export interface Video {
  title: string;
  description: string;
  url: string;
  tags: string[];
  duration: string;
  author: string;
  thumbnailUrl: string;
}

export const videos: Video[] = [
  // --- XI Chemistry Videos ---
  
  // Physics (MDCAT/ECAT)
  {
    title: "Complete Physics Playlist | 11",
    description: "Complete Physics Playlist for ECAT | NET | MDCAT | NUMS | AKU All Chapters.",
    url: "http://www.youtube.com/playlist?list=PLG6V3xWznon93t0CIAhcGPcOaVhiF64td",
    tags: ["Physics", "MDCAT", "ECAT", "11th Grade", "Playlist"],
    duration: "N/A",
    author: "Physics Ka Manjan - Bilal Zia",
    thumbnailUrl: "https://img.youtube.com/vi/8t82rUkNMOg/hqdefault.jpg",
  },
  {
    title: "Complete Physics Playlist | 12",
    description: "Complete Physics Playlist for ECAT | NET | MDCAT | NUMS | AKU All Chapters.",
    url: "http://www.youtube.com/playlist?list=PLG6V3xWznon_XbF37f_iACsbl5CxMebLZ",
    tags: ["Physics", "MDCAT", "ECAT", "12th Grade", "Playlist"],
    duration: "N/A",
    author: "Physics Ka Manjan - Bilal Zia",
    thumbnailUrl: "https://img.youtube.com/vi/8t82rUkNMOg/hqdefault.jpg",
  },
  {
    title: "MDCAT & NUMS Physics Complete Playlist",
    description: "Complete conceptual Physics lectures and preparations for MDCAT & NUMS.",
    url: "http://www.youtube.com/playlist?list=PLTHu-Jj65TBBwIlJK4ENTMZjR1mdjllQM",
    tags: ["Physics", "MDCAT", "NUMS", "Playlist"],
    duration: "N/A",
    author: "Physics In Seconds - Ustaad Jee",
    thumbnailUrl: "https://img.youtube.com/vi/n1U4djN6urc/hqdefault.jpg",
  },

  // Chemistry (MDCAT)
  {
    title: "MDCAT CHEMISTRY - ONE SHOT LECTURES",
    description: "Complete MDCAT Chemistry one-shot conceptual revision lectures.",
    url: "http://www.youtube.com/playlist?list=PLHlpPled54RdDt8Ey-l7KmOkNHWE2FFGy",
    tags: ["Chemistry", "MDCAT", "One Shot", "Playlist"],
    duration: "N/A",
    author: "Easy Science - Sir Samiullah",
    thumbnailUrl: "https://img.youtube.com/vi/Peozxl1joeQ/hqdefault.jpg",
  },
  {
    title: "MDCAT Chapter-wise Past Papers Solution",
    description: "Focussed on solving all MDCAT Chemistry past papers chapter wise and topic wise.",
    url: "http://www.youtube.com/playlist?list=PLCAYTz5LAz-SQVzHV_mkcwir60qkW6bwW",
    tags: ["Chemistry", "MDCAT", "Past Papers", "Playlist"],
    duration: "N/A",
    author: "Kifayat Chemistry Lectures",
    thumbnailUrl: "https://img.youtube.com/vi/oFj_v1NEv_o/hqdefault.jpg",
  },

  // Mathematics (ECAT/NET)
  {
    title: "ECAT / NET MATHS LECTURES",
    description: "Engineering Colleges Aptitude Test Mathematics (E-CAT MATHS) for NUST, FAST, UET.",
    url: "http://www.youtube.com/playlist?list=PL5b9mn6-ELrGIsc3LVnFEzlN1fs75Ay--",
    tags: ["Math", "ECAT", "NET", "Playlist"],
    duration: "N/A",
    author: "Mathsflix By Hashim Zia",
    thumbnailUrl: "https://img.youtube.com/vi/a-LYvdQZxeY/hqdefault.jpg",
  },
  {
    title: "ECAT Class 11 and 12 all chapters mathematics",
    description: "Complete Mathematics ECAT lectures for class 11 and 12.",
    url: "http://www.youtube.com/playlist?list=PLw-N3BrmIFx5sg4N2EpKBdwW09GHwFf1_",
    tags: ["Math", "ECAT", "11th Grade", "12th Grade", "Playlist"],
    duration: "N/A",
    author: "ME English Center",
    thumbnailUrl: "https://img.youtube.com/vi/oH0KXdj0pI8/hqdefault.jpg",
  },

  // English (MDCAT)
  {
    title: "MDCAT English One Shot Series",
    description: "Complete MDCAT English Preparation. Covers grammar rules, vocabulary, and structuring.",
    url: "http://www.youtube.com/playlist?list=PL4nFCgRRw9ZZ3BN9LOWlLoZmta_U2Yf3s",
    tags: ["English", "MDCAT", "One Shot", "Playlist"],
    duration: "N/A",
    author: "English with Sir Azeem",
    thumbnailUrl: "https://img.youtube.com/vi/qzWplQ-d_TM/hqdefault.jpg",
  },
  {
    title: "MDCAT English Syllabus By Naseer Abbas",
    description: "Comprehensive English syllabus preparation for MDCAT.",
    url: "http://www.youtube.com/playlist?list=PLJoUxx3Cyw7bR7ttWPj0mNYJBe4LYLwx5",
    tags: ["English", "MDCAT", "Playlist"],
    duration: "N/A",
    author: "Beacon Stars",
    thumbnailUrl: "https://img.youtube.com/vi/GobseQUh0c0/hqdefault.jpg",
  },
  {
    title: "Chapter 01 to 08 Numerical Workshop Tricks and Tips (Playlist)",
    description: "Playlist for XI Chemistry numerical workshop tricks and tips for chapters 1 to 8.",
    url: "https://www.youtube.com/playlist?list=PLPEO6M6KVHIghHxp9R2Nukk00EiorS-Ho",
    tags: ["XI Chemistry", "Numericals", "Tricks", "Playlist"],
    duration: "N/A", 
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/nj_5T-orE2c/hqdefault.jpg", // Uses the first video's thumbnail as cover
  },
  {
    title: "Hydrogen Spectrum Tricks",
    description: "Tricks to understand and solve questions related to the Hydrogen Spectrum.",
    url: "https://youtu.be/nj_5T-orE2c",
    tags: ["XI Chemistry", "Hydrogen Spectrum", "Tricks"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/nj_5T-orE2c/hqdefault.jpg",
  },
  {
    title: "How to calculate Electron, Proton and Neutron",
    description: "Learn the easy way to calculate the number of electrons, protons, and neutrons.",
    url: "https://youtu.be/wL5VNycj5I4",
    tags: ["XI Chemistry", "Atomic Structure", "Protons", "Neutrons", "Electrons"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/wL5VNycj5I4/hqdefault.jpg",
  },
  {
    title: "How to calculate oxidation number",
    description: "Step-by-step guide and tricks to calculate oxidation numbers.",
    url: "https://youtu.be/mYvyTjhDql0",
    tags: ["XI Chemistry", "Oxidation Number", "Redox"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/mYvyTjhDql0/hqdefault.jpg",
  },
  {
    title: "How to calculate sigma and pi bond",
    description: "Tricks to quickly count sigma and pi bonds in chemical structures.",
    url: "https://youtu.be/zSyknBlN7Ho",
    tags: ["XI Chemistry", "Chemical Bonding", "Sigma Bond", "Pi Bond"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/zSyknBlN7Ho/hqdefault.jpg",
  },
  {
    title: "How to calculate Hybridization",
    description: "Shortcuts and tricks for finding the hybridization of molecules.",
    url: "https://youtu.be/s-VaedDVgQ0",
    tags: ["XI Chemistry", "Hybridization", "Chemical Bonding"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/s-VaedDVgQ0/hqdefault.jpg",
  },
  {
    title: "Trick for Ksp Numerical",
    description: "Easy tricks to solve Solubility Product Constant (Ksp) numericals.",
    url: "https://youtu.be/i-7MfTsw2hw",
    tags: ["XI Chemistry", "Equilibrium", "Ksp", "Numericals"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/i-7MfTsw2hw/hqdefault.jpg",
  },
  {
    title: "pH without Calculator",
    description: "Learn how to calculate pH values manually without using a calculator.",
    url: "https://youtu.be/NCEUZfB2upQ",
    tags: ["XI Chemistry", "pH", "Calculation", "Acids and Bases"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/NCEUZfB2upQ/hqdefault.jpg",
  },
  {
    title: "Le Chatelier’s Principle",
    description: "Detailed explanation and tricks for Le Chatelier's Principle.",
    url: "https://youtu.be/enXjjGp5HkA",
    tags: ["XI Chemistry", "Chemical Equilibrium", "Le Chatelier"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/enXjjGp5HkA/hqdefault.jpg",
  },

  // --- XII Chemistry Videos ---
  {
    title: "How to determine Block Group and Period",
    description: "Tricks to find the block, group, and period of elements in the periodic table.",
    url: "https://youtu.be/gtWtRRM2v0I",
    tags: ["XII Chemistry", "Periodic Table", "Elements"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/gtWtRRM2v0I/hqdefault.jpg",
  },
  {
    title: "Group Trends Tricks",
    description: "Easy ways to memorize and understand group trends in the periodic table.",
    url: "https://youtu.be/_LlSIHbCcJ8",
    tags: ["XII Chemistry", "Periodic Trends", "Inorganic Chemistry"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/_LlSIHbCcJ8/hqdefault.jpg",
  },
  {
    title: "S Block Explanation",
    description: "Comprehensive explanation of S Block elements and their properties.",
    url: "https://youtu.be/C4L5kM58BF0",
    tags: ["XII Chemistry", "S Block", "Inorganic Chemistry"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/C4L5kM58BF0/hqdefault.jpg",
  },
  {
    title: "IUPAC Inorganic Trick",
    description: "Tricks for IUPAC nomenclature of inorganic compounds.",
    url: "https://youtu.be/ieqXyZaOsuc",
    tags: ["XII Chemistry", "IUPAC", "Inorganic Nomenclature"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/ieqXyZaOsuc/hqdefault.jpg",
  },
  {
    title: "How to learn Catalyst of Organic Reactions",
    description: "Memorization tricks for catalysts used in various organic reactions.",
    url: "https://youtu.be/RCRz6TvZCXA",
    tags: ["XII Chemistry", "Organic Chemistry", "Catalysts"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/RCRz6TvZCXA/hqdefault.jpg",
  },
  {
    title: "IUPAC Organic Rules",
    description: "Rules and tricks for IUPAC naming of organic compounds.",
    url: "https://youtu.be/6UfXBT_pFaM",
    tags: ["XII Chemistry", "Organic Chemistry", "IUPAC Naming"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/6UfXBT_pFaM/hqdefault.jpg",
  },
  {
    title: "Trick to Find Isomers",
    description: "Quick trick to calculate and find isomers in organic chemistry.",
    url: "https://youtu.be/6t9sx9hDNTs",
    tags: ["XII Chemistry", "Organic Chemistry", "Isomerism"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/6t9sx9hDNTs/hqdefault.jpg",
  },
  {
    title: "Reactions of Alkanes",
    description: "Key reactions of alkanes explained simply.",
    url: "https://youtu.be/QrWTqlcI6gI",
    tags: ["XII Chemistry", "Organic Chemistry", "Alkanes"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/QrWTqlcI6gI/hqdefault.jpg",
  },
  {
    title: "Reactions of Alkenes",
    description: "Key reactions of alkenes explained simply.",
    url: "https://youtu.be/pYuQzQnILaE",
    tags: ["XII Chemistry", "Organic Chemistry", "Alkenes"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/pYuQzQnILaE/hqdefault.jpg",
  },
  {
    title: "Reactions of Alkynes",
    description: "Key reactions of alkynes explained simply.",
    url: "https://youtu.be/IyQLcLw7rZI",
    tags: ["XII Chemistry", "Organic Chemistry", "Alkynes"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/IyQLcLw7rZI/hqdefault.jpg",
  },
  {
    title: "Benzene Explanation",
    description: "Detailed explanation of Benzene structure and properties.",
    url: "https://youtu.be/I1QdCo9IxUM",
    tags: ["XII Chemistry", "Organic Chemistry", "Benzene", "Aromatic"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/I1QdCo9IxUM/hqdefault.jpg",
  },
  {
    title: "Reactions of Grignard’s Reagent",
    description: "How to solve reactions involving Grignard's Reagent.",
    url: "https://youtu.be/6Lrl5xh1N-U",
    tags: ["XII Chemistry", "Organic Chemistry", "Grignard Reagent"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/6Lrl5xh1N-U/hqdefault.jpg",
  },
  {
    title: "SN and E Reactions",
    description: "Explanation of Substitution (SN1, SN2) and Elimination (E1, E2) reactions.",
    url: "https://youtu.be/A6thlwbV8Qs",
    tags: ["XII Chemistry", "Organic Chemistry", "SN Reactions", "Elimination Reactions"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/A6thlwbV8Qs/hqdefault.jpg",
  },

  // --- XI Physics Videos ---
  {
    title: "Complete Chapter Tricks and Tips for Numerical Chapter 01 to 10 (Playlist)",
    description: "Playlist for XI Physics complete chapter tricks and tips for numericals from chapters 1 to 10.",
    url: "https://www.youtube.com/playlist?list=PLPEO6M6KVHIg6Bmv_0l3SMKpCHROZiqvU",
    tags: ["XI Physics", "Numericals", "Tricks", "Playlist"],
    duration: "N/A",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/i41Q6dmtbLM/hqdefault.jpg", // Uses the first video's thumbnail
  },
  {
    title: "Tips and Tricks for Physics Numerical",
    description: "General tips and tricks to solve physics numericals quickly.",
    url: "https://youtu.be/i41Q6dmtbLM",
    tags: ["XI Physics", "Numericals", "Tricks"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/i41Q6dmtbLM/hqdefault.jpg",
  },
  {
    title: "Cross Product Trick",
    description: "Easy way to calculate the cross product of vectors.",
    url: "https://youtu.be/NrDYfC1RDJM",
    tags: ["XI Physics", "Vectors", "Cross Product", "Math Tricks"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/NrDYfC1RDJM/hqdefault.jpg",
  },
  {
    title: "Concave Mirror MCQs tricks",
    description: "Tricks to solve multiple-choice questions related to concave mirrors.",
    url: "https://youtu.be/kRI1-_Tz2x0",
    tags: ["XI Physics", "Optics", "Concave Mirror", "MCQs"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/kRI1-_Tz2x0/hqdefault.jpg",
  },
  {
    title: "Doppler’s Effect Trick",
    description: "Shortcuts to solve Doppler's effect problems in physics.",
    url: "https://youtu.be/B2DdBI90FO8",
    tags: ["XI Physics", "Waves", "Doppler Effect", "Tricks"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/B2DdBI90FO8/hqdefault.jpg",
  },

  // --- XII Physics Videos ---
  {
    title: "How to take square without calculator",
    description: "Math trick to calculate squares without a calculator, useful for physics numericals.",
    url: "https://youtu.be/IR5XpS_u3Ig",
    tags: ["XII Physics", "Math Tricks", "Calculations"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/IR5XpS_u3Ig/hqdefault.jpg",
  },
  {
    title: "Capacitor",
    description: "Complete explanation and tips for solving capacitor problems.",
    url: "https://youtu.be/tAUpLIwvB3o",
    tags: ["XII Physics", "Electrostatics", "Capacitor"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/tAUpLIwvB3o/hqdefault.jpg",
  },
  {
    title: "Galvanometer and conversions",
    description: "Explanation of galvanometer and its conversion into ammeter and voltmeter.",
    url: "https://youtu.be/d2mhvldyJ2Y",
    tags: ["XII Physics", "Electromagnetism", "Galvanometer"],
    duration: "00:00",
    author: "Author Name",
    thumbnailUrl: "https://img.youtube.com/vi/d2mhvldyJ2Y/hqdefault.jpg",
  },

  
];